WorkspaceId:
  name: workspace_id
  in: query
  description: 空间ID
  required: true
  schema:
    type: string
    example: 1234567890

Category:
  name: category
  in: query
  description: 文件类别
  required: false
  schema:
    type: string
    example: invoice

BatchNumber:
  name: batch_number
  in: query
  description: |
    批次编号。  
    可以用同一个批次编号上传多次，后续可以用批次编号获取该批次多个文件处理结果。  
    如果值为空，则系统自动生成最长20位字符串
  required: false
  schema:
    type: string
    example: 202412190001

AutoVerifyVat:
  name: auto_verify_vat
  in: query
  description: 是否自动进行发票验真
  required: false
  schema:
    type: boolean
    default: false

SplitFlag:
  name: split_flag
  in: query
  description: 是否进行文件拆分
  required: false
  schema:
    type: boolean
    default: false

CropFlag:
  name: crop_flag
  in: query
  description: 是否进行多图切分
  required: false
  schema:
    type: boolean
    default: false

TargetProcess:
  name: target_process
  in: query
  description: |
    目标处理类型。  
    可选值：  
    - `classify`: 分类  
    - `extract`: 抽取  
  required: false
  schema:
    type: string
    enum:
      - classify
      - extract
    example: classify

ParserRemoveWatermark:
  name: parser_remove_watermark
  in: query
  description: 是否去水印（0:不去水印、1:去水印）
  required: false
  schema:
    type: integer
    default: 0

ParserCropDewarp:
  name: parser_crop_dewarp
  in: query
  description: 是否进行切边矫正（0:不进行切边矫正、1:进行切边矫正）
  required: false
  schema:
    type: integer
    default: 0

ParserApplyMerge:
  name: parser_apply_merge
  in: query
  description: 是否进行跨页段落表格合并（0:不合并、1:合并）
  required: false
  schema:
    type: integer
    default: 1

ParserFormulaLevel:
  name: parser_formula_level
  in: query
  description: 公式识别等级(0 行间公式和行内公式都识别、1 仅识别行间公式，行内公式不识别、2 不识别公式)
  required: false
  schema:
    type: integer
    default: 0

ParserTableTextSplitMode:
  name: parser_table_text_split_mode
  in: query
  description: 表格线是否分割ocr文本（0:不切割、1:切割）
  required: false
  schema:
    type: integer
    default: 0

WithTaskDetailUrl:
  name: with_task_detail_url
  in: query
  description: 是否返回任务详情页URL
  required: false
  schema:
    type: boolean
    default: false
